default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: acid-auth-ws2_development

test:
  <<: *default
  database: acid-auth-ws2_test

production:
  <<: *default
  database: acid-auth-ws2_production
  username: acid-auth-ws2
  password: <%= ENV['ACID-AUTH-WS2_DATABASE_PASSWORD'] %>
